### ISSUE TITLE
too many 3-6 somy CNV calls from single cell DNA-seq

### ISSUE THREAD

**Issue by shouguog** [ataudt/aneufinder#10]
I am using aneufinder to analyze single cell data with default parameters.

For most of cells from healthy donors (assumed with only a small number of copy number variation), only a few called CNVs are not "2somy", which is as expected. 

However for around 5% of cells, most of called CNVs are not "2 somy", as shown in attached file.

Is there any problem with the result? 

[cell73.txt](https://github.com/ataudt/aneufinder/files/6136954/cell73.txt)

**Comment by ataudt** [comment]
Hi shouguog,

my guess is that the single cell data for these cells is not clean enough (multiple cells pooled together instead of single cells). Low quality sequencing data of a fraction of the sequenced cells, due to various reasons, is a known problem. Therefore, we have included a quality control step in the AneuFinder pipeline. Please see the vignette section 3.6 for further details.
https://bioconductor.org/packages/release/bioc/vignettes/AneuFinder/inst/doc/AneuFinder.pdf

I hope this solves the issue.

Best,
Aaron
